site_name: Antior 
repo_url: https://github.com/midnightprioriem/antior-worldbuilding
use_directory_urls: True 
markdown_extensions:
        - smarty
        - admonition
        - mdx_truly_sane_lists
        - attr_list
        - extra
extra_css:
        - css/codehilite.css
        - css/sidebar.css
        - css/link-tooltips.css
        - css/tooltipster.bundle.min.css
        - css/tooltipster-sideTip-shadow.min.css
        - css/mkdocs-material-themes/gruvbox_colors.css
        - css/mkdocs-material-themes/material_theme.css
extra_javascript:
        - js/tooltipster.bundle.js 
        - js/humblehr.js
theme: 
        name: material
        custom_dir: 'theme'
        logo: 
                icon: 'public'
plugins:
        - search
        - macros
        - autolinks
        - toc-sidebar
        - tooltipster-links 
        - vim-md-tags 

nav:
